services:
  php:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html   # Mount only ./api to avoid mismatches
    environment:
      APP_ENV: prod
      APP_DEBUG: 0

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./api/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  web:
    build: ./web/
    ports:
      - "8080:8080"